src/__tests__/strings.test.ts, src/numbers.ts, src/strings.ts, src/types.ts
see https://github.com/gcanti/io-ts/issues/97\#issuecomment-388390586
=> Tentative fix for issue with tagged types.

package.json, src/__tests__/responses.test.ts, src/responses.ts, yarn.lock
I've changed HTTP_STATUS_XXX constants into an enum.
ProblemJson, which is now "hardcoded", should come from the api specs (definitions.yaml).
Maybe it's worth to move that yaml into this repo as well ? (with another PR)
=> [#157849558] added HTTP responses

package.json, src/responses.ts, src/url.ts
aside fixes package.json version to match npm package (incremented beforewards but wrongly not pushed)
=> [#157875848] chore: add xml response

package.json, src/__tests__/requests.test.ts, src/requests.ts, tsconfig.json
fix to request encoder to support types like DateFromString
=> [#157875866] fix request decoder type

tsconfig.json
sets same target as the one used in functions
https://github.com/basarat/typescript-book/blob/master/docs/types/lib.d.ts.md#lib-option
=> fix: typescript target

package.json, src/__tests__/express.test.ts, src/express.ts
ref. https://github.com/teamdigitale/italia-backend/blob/master/src/app.ts#L70
=> added: to express handler

src/__tests__/number.test.ts, src/__tests__/pagopa.test.ts, src/numbers.ts, src/pagopa.ts, src/strings.ts
1. renamed CodiceSegregazione -> segregationCode
1. added type for QrCode string
1. added WithinRangeInteger / NonNegativeInteger to handle integers from swagger specs
1. added FiscalCode and OrganizationFiscalCode types
=> [#158476864] add qrcode custom type

package.json, src/__tests__/request_middleware.test.ts, src/request_middleware.ts, tslint.json, yarn.lock
note that this introduces a dependency on winston
=> [#158528448] added request middlewares

src/__tests__/requests.test.ts, src/fetch.ts, src/requests.ts, src/tasks.ts, tsconfig.json
This fixes an issue that was making the retry logic not wait for delay before retrying.
=> Fix retries

package.json, src/pagopa.ts, yarn.lock
Also fixes compile errors for pagopa types
=> Upgrades to typescript 3

package.json, yarn.lock
see https://github.com/gcanti/io-ts/issues/315
=> Upgrades io-ts to 1.8.5 to fix compatibility with ts-3.4.1

src/responses.ts
Detail message can be used to log additional
details about a response.
=> Adds detail message to responses

src/__tests__/requests.test.ts, src/requests.ts
this PR aims to add a processor function to basic decoder.
In this way the response can be altered before the decoder gives it back.
=> add pre-processor to basic decoder

src/responses.ts
[#157896066] - Implement 429 too many requests return code.
=> [#157896066] Adds a response type for HTTP status 429.

src/responses.ts
Fix deprecated usage of response redirect.
=> [#165794965] Fixes deprecated usage of Express redirect response.

src/responses.ts
Make the 'detail' param in ResponseErrorTooManyRequests as an optional parameter
=> 157896066-too-many-request

src/__tests__/tasks.test.ts, src/tasks.ts
=> Fix: withRetries called twice on permanent error

src/units.ts
Added the following unit types:
* Minute
* Hour
* day
=> [#173394178] add time units

src/__tests__/request_middleware.test.ts, src/request_middleware.ts
Increase the maximum number of middlewares that can be piped to 7
=> [IP-215] Add 7th middleware to `withRequestMiddlewares`

src/__tests__/dates.test.ts, src/dates.ts
This PR adds a brand new decoder for parsing Dates against Timestamp format.
=> add timestamp decoder

package.json, yarn.lock
=> [#IP-325] Upgrade Typescript to v4.3.5

src/__tests__/booleans.test.ts, src/booleans.ts
We need to convert a string to boolean when dealing with request's parameters.
Added tests for codec.
=> [#IP-362] Added a codec to support conversion from string to boolean

src/__tests__/types.test.ts, src/types.ts
Additional tests for https://github.com/pagopa/io-ts-commons/pull/370
=> More tests on `Head<T>`, `Tail<T>` and `HasTail<T>` 

.github/PULL_REQUEST_TEMPLATE.md, src/__tests__/strings.test.ts, src/strings.ts
Add new Semver type
Pull request template
To add the last used app version into the user profile we need a new regex based type.
unit test
=> [#IOCIT-14] New Semver type

src/responses.ts
Added `IResponseSuccessNoContent` type and `ResponseSuccessNoContent` function
Provide utility methods for the `204 No Content` HTTP response
=> [#IOCIT-83] Added utilities for the HTTP 204 response

src/__tests__/responses.test.ts, src/responses.ts
* added `getResponseErrorForbiddenNotAuthorized`
* added `getResponseErrorForbiddenNoAuthorizationGroups`
* added some unit test 
In order to get the possibility to specify the detail of a `ResponseErrorForbiddenNotAuthorized` and a `getResponseErrorForbiddenNoAuthorizationGroups`  I have added 2 functions that return those 2 types with a custom and optional detail.
unit test
=> [ICC-168] Adding custom details on errors

src/__tests__/jwk.test.ts, src/jwk.ts
Required in order to provide strict validation on JwkPubKey types
Unit Test
=> [#IOCIT-241] Add exact to JWK Decoders

package.json, src/__tests__/http-user-agent.test.ts, src/http-user-agent.ts, yarn.lock
- `http-user-agent` custom decoders
Added a Custom decoder that turns a User agent string format into a typed object
Unit test
=> [#IOCIT-241] Add SemverFromUserAgentString Custom decoder

.devops/code-review-pipelines.yml, src/__tests__/strings.test.ts, src/strings.ts
=> [#IOCIT-162] Added type for ulid strings

src/__tests__/sequence_middleware.test.ts, src/sequence_middleware.ts
New SequenceMiddleware that executes two middleware in sequence, and return an *IRequestMiddleware* of:
- the first middleware **R0** result if both middlewares return an Either Right
- the second middleware **R1** result if only second middleware return an Either Right
- the **default error** if both middlewares return a Promise of an Either Left or an execution error
- Added new SequenceMiddleware
- Added related tests
We need to execute two middleware at the same time, and potentially, only one of them return a *Right* result.
For example, as part of the **MANAGE Flow** management, and for a certain period of duality of actual and new operation, we need to run two middlewares *(AzureUserAttributeMiddleware, AzureUserAttributeManageMiddleware)* and only one of them should return a …
=> [#IOPAE-148] Add SequenceMiddleware

src/requests.ts
Extend body type in Request with `ReadableStream<UInt8Array>`
If we want to send a raw body if a `ReadableStream` can be provided as valid type
not tested
=> Extend the body in responses with raw ReadableStream

src/responses.ts
* added 502 and 504 error responses
ready for use
=> [#IOPID-734] add gateway error responses

src/responses.ts
1. Add `ResponseErrorPreconditionFailed` that returns an `HTTP 412` error
This error will be returned by `UpdateProfile` when the chosen e-mail is already taken
=> [IOPID-1258] Add error 412 (Precondition Failed)

src/hash.ts
Add a new module (`hash.ts`) that exports `hashFiscalCode` functions that hashes (usign `sha256`) a fiscal code.
Right now there are two identical implementations of this utility function, in `io-backend` and `io-functions-app-messages`. Since it is also needed in `io-functions-admin` and `io-functions-public` it better to centralize this implementation here.
=> [IOPID-1296] Add hashFiscalCode function 

package.json, yarn.lock
The dependencies `io-ts` and `fp-ts` are moved into `peerDependencies`.
Upgrade some dependency.
Now the consumer of this library can choose the version at the project level avoiding library conflicts over `io-ts` and `fp-ts` combinations.
Tested linking this library with `io-functions-commons` locally and executing build and tests.
=> [#DEVEX-60] Move fp-ts io-ts to peerDeps and upgrade deps

src/appinsights.ts
=> Restore live metrics

src/url.ts
Fix type `HttpUrlFromString` declaration.
The type `HttpUrlFromString` is using the validation written for the HTTPS protocol.
Unit tests.
=> fix: type `HttpUrlFromString`
